# Generated by Django 2.2.5 on 2019-11-13 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dogtag_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purcahsed_at',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 13, 16, 3, 49, 389975)),
        ),
    ]
