# Generated by Django 2.2.5 on 2019-11-13 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191113_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purcahsed_at',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateField(default=datetime.datetime(2019, 11, 13, 17, 25, 47, 703237, tzinfo=utc), verbose_name=datetime.datetime(2019, 11, 13, 17, 23, 51, 421222)),
            preserve_default=False,
        ),
    ]
