# Generated by Django 2.2.5 on 2019-11-13 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191113_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 13, 17, 26, 44, 83379)),
        ),
    ]
