# Generated by Django 2.2.5 on 2019-11-15 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191113_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 15, 18, 53, 13, 824878)),
        ),
    ]
