# Generated by Django 2.2.5 on 2019-11-15 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191115_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogtag',
            name='owner_address',
            field=models.TextField(default=datetime.datetime(2019, 11, 15, 18, 56, 38, 829117, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 15, 18, 56, 14, 817703)),
        ),
    ]
