# Generated by Django 2.2.5 on 2019-11-15 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191115_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 15, 19, 9, 40, 580414)),
        ),
    ]
